name: verify-app
description: Verifies the frontend application using Playwright
run: |
    # Install dependencies
    pip install playwright pytest pytest-playwright
    playwright install chromium

    # Start the server in the background
    python3 -m http.server 8000 &
    SERVER_PID=$!

    # Wait for server to start
    sleep 2

    # Run the verification script
    python3 verification/verify_slides.py

    # Clean up
    kill $SERVER_PID
